"""
style.py

Shared Matplotlib styling for the figures generated by attack_surface.py,
latency_model.py, and t8_t9_resilience.py. Centralizes the color palette
and a small set of formatting helpers so all three figures render with
consistent, colorblind-safe, print-safe styling.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------
# Palette (colorblind-safe, print-safe)
# ---------------------------------------------------------------------
INK = '#1F2937'       # primary text / axis ink
BASELINE = '#94A3B8'  # neutral baseline / comparison series
ACCENT = '#0EA5E9'    # primary highlight series
GOOD = '#10B981'      # favorable outcome (e.g. ZTDC-IoT, unknown-state)
WARN = '#F59E0B'      # caution / boundary marker
BAD = '#EF4444'       # unfavorable outcome (e.g. baseline attack success)
VIOLET = '#8B5CF6'    # secondary highlight series

FONT_FAMILY = 'DejaVu Sans'


def apply_style():
    """Sets the global rcParams used by all figures in this repository.
    Call once before creating any figure."""
    plt.rcParams.update({
        'font.family': FONT_FAMILY,
        'font.size': 10,
        'axes.edgecolor': INK,
        'axes.labelcolor': INK,
        'text.color': INK,
        'xtick.color': INK,
        'ytick.color': INK,
        'axes.titlesize': 11,
        'axes.titleweight': 'bold',
        'axes.labelsize': 10,
        'legend.frameon': False,
        'legend.fontsize': 9,
        'figure.facecolor': 'white',
        'axes.facecolor': 'white',
        'savefig.facecolor': 'white',
        'axes.grid': True,
        'grid.color': '#E5E7EB',
        'grid.linewidth': 0.6,
        'grid.alpha': 0.8,
    })


def clean_axes(ax):
    """Removes chart-junk: top/right spines, and thins the remaining
    spines to match the ink color."""
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color(INK)
    ax.spines['bottom'].set_color(INK)
    ax.spines['left'].set_linewidth(0.8)
    ax.spines['bottom'].set_linewidth(0.8)
    ax.set_axisbelow(True)


def value_label(ax, x, y, text, offset=0.01, **kwargs):
    """Places a direct value annotation above a bar/point at (x, y),
    offset by a fraction of the axis range so labels stay legible."""
    ylim = ax.get_ylim()
    dy = (ylim[1] - ylim[0]) * offset
    defaults = dict(ha='center', va='bottom', fontsize=9, color=INK)
    defaults.update(kwargs)
    ax.text(x, y + dy, text, **defaults)


def footnote(fig, text, y=-0.04, fontsize=7.5):
    """Adds a small italic methodological footnote below a figure."""
    fig.text(0.5, y, text, wrap=True, ha='center', va='top',
              fontsize=fontsize, style='italic', color=INK)
