name: Print Hello in Python

on:
  workflow_dispatch: # Adds the manual "Run workflow" button

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # This tells the terminal to run an inline Python print command
     Moss-name: Execute Python Print
      run: python -c "print('Hello from Python!')"
